App:
  ListenerAddress: 0.0.0.0:8081
  WorkDir: ./.workdata

Cess:
  RpcUrl: ws://221.122.79.5:9944/
  SecretPhrase: "hire useless peanut engine amused fuel wet toddler list party salmon dream"
  ChainId: 11330

Cessfsc:
  BootAddrs:
    - "_dnsaddr.boot-bucket-testnet.cess.cloud"
  P2pPort: 138001